substitutions:
  name:           "sensor-pkg-a-c4001"
  friendly_name:  "Indoor Multi-Sensor Pkg A Radar C4001"

  # Settings
  use_pir_in_presence:      "true"
  # Status LED configuration
  status_day_brightness:    "0.5"
  status_night_brightness:  "0.20"
  status_daytime_lux:       "12.0"
  status_nighttime_lux:     "7.0"
  # CO configuration
  co_temp_id:               "temperature"
  co_offset:                "0.0"
  co_sensitivity:           "2.000e-9"
  co_manufacture_date:      "01/01/1999"
  co_serial_number:         "111111111111111111"
  # SEN6X Configuration
  sen6x_temperature_offset: "0.0"
  sen6x_humidity_offset:    "0.0"
  sen6x_output_rate:        "60s"
  sen6x_calibration_date:   "01/01/1999"
  # INA2XX Configuration
  INA2XX_output_rate:       "60s"
  # Automatically controlled Vent
  vent_ha_entity:           fan.vent_id
  vent_use_humidity:        "true"
  vent_use_co2:             "true"
  vent_min_on_time:         "15"
  vent_hum_on_trigger:      "10.0"
  vent_hum_off_trigger:     "2.5"
  vent_co2_on_trigger:      "1100"
  vent_co2_off_trigger:     "900"

packages:
  # COMMON
  common:                   !include github://mikelawrence/ESPHome-Multi-Test/config/common/common.yaml

  # SENSORS - PACKAGE A - Sensirion SEN66
  sen6x_pkga:               !include github://mikelawrence/ESPHome-Multi-Test/config/common/pkga-sen6x.yaml

  # MMWAVE SENSOR - DFRobot C4001 (SENS0609 or SEN0610) - Mike Custom Component
  c4001_radar:              !include github://mikelawrence/ESPHome-Multi-Test/config/common/radar-c4001.yaml

  # ADDITIONAL SENSORS
  # Carbon Dioxide (CO) - Figaro TGS5141 sensor
  co_add:                   !include github://mikelawrence/ESPHome-Multi-Test/config/common/add-co.yaml
  # Energy Usage - INA2XX sensor to measure Voltage, Power and Energy Usage
  ina2xx_add:               !include github://mikelawrence/ESPHome-Multi-Test/config/common/add-ina2xx.yaml
  # Light Level - TSL2591 sensor
  tsl2591_add:              !include github://mikelawrence/ESPHome-Multi-Test/config/common/add-tsl2591.yaml
  # Barometric Pressure - BMP581 sensor
  bmp581_add:               !include github://mikelawrence/ESPHome-Multi-Test/config/common/add-bmp581.yaml
  # Speaker - Adds audio output and Media Player
  speaker_add:              !include github://mikelawrence/ESPHome-Multi-Test/config/common/add-speaker.yaml
  # Microphone - Adds Sound Level meter
  microphone_add:           !include github://mikelawrence/ESPHome-Multi-Test/config/common/add-microphone.yaml

  # FEATURES
  # SEN6X Pressure Compensation - Adds pressure compensation to SEN6X
  sen6x_pres_comp_feat:     !include github://mikelawrence/ESPHome-Multi-Test/config/common/feat-sen6x-press-comp.yaml
  # Automatic Vent - Use humidity and CO₂ control a bathroom vent
  # auto_vent_feat:           !include github://mikelawrence/ESPHome-Multi-Test/config/common/feat-auto-vent.yaml

# Add custom components
external_components:
  - source: github://mikelawrence/esphome-components@main
    components: [dfrobot_c4001, sen5x, bmp581]

esphome:
  name: "sensor-pkg-a-c4001"
  friendly_name: "Sensor Pkg A Radar C4001"
  name_add_mac_suffix: false

# ESP32-S3-WROOM-2-N32R16V
esp32:
  board: esp32s3box
  variant: ESP32S3
  flash_size: 32MB
  cpu_frequency: 240MHz
  framework:
    type: esp-idf

# This PSRAM can actually support faster than 80MHz
psram:
  mode: octal
  speed: 80MHz

# To be able to get logs from the device via serial and api.
logger:
  id: logger_common
  level: DEBUG

# API is a requirement of the dashboard import.
api:

# OTA is required for Over-the-Air updating
ota:
  - platform: esphome
    id: ota_esphome

wifi:
  # Set up a wifi access point using the device name above
  ap:

esp32_ble_tracker:
  scan_parameters:
    active: true

bluetooth_proxy:
  active: true
