
i2s_audio:
  - id: speaker_i2s
    i2s_lrclk_pin: GPIO12
    i2s_bclk_pin: GPIO11

media_player:
  - platform: speaker
    name: "Speaker Media Player"
    id: speaker_media_player_id
    media_pipeline:
      speaker: media_spk_resampling_input
      num_channels: 2
    announcement_pipeline:
      speaker: announcement_spk_resampling_input
      num_channels: 1
    # files:
    #   - id: smoke_alarm_sound
    #     file: indoor-multi-sensor/fast-beep.flac
    #   - id: co_alarm_sound
    #     file: indoor-multi-sensor/CO-alarm-message.mp3

power_supply:
  - id: dac_enable
    pin: GPIO9
    enable_on_boot: true

speaker:
  - platform: i2s_audio
    id: speaker_id
    i2s_audio_id: speaker_i2s
    dac_type: external
    i2s_dout_pin: GPIO10
    sample_rate: 48000
  - platform: mixer
    id: mixer_speaker_id
    output_speaker: speaker_id
    source_speakers:
      - id: announcement_spk_mixer_input
      - id: media_spk_mixer_input
  - platform: resampler
    id: media_spk_resampling_input
    output_speaker: media_spk_mixer_input
    sample_rate: 48000
  - platform: resampler
    id: announcement_spk_resampling_input
    output_speaker: announcement_spk_mixer_input
    sample_rate: 48000

switch:
  - platform: template
    name: "Ring Timer"
    id: timer_ringing
    optimistic: true
    restore_mode: ALWAYS_OFF
    on_turn_off:
        # Stop playing the alarm
        - media_player.stop:
            announcement: true
        - mixer_speaker.apply_ducking:  # Stop ducking the media stream over 2 seconds
            id: media_spk_mixer_input
            decibel_reduction: 0
            duration: 2.0s
    on_turn_on:
        # Duck media audio by 20 decibels instantly
        - mixer_speaker.apply_ducking:
            id: media_spk_mixer_input
            decibel_reduction: 20
            duration: 0.0s
        - while:
            condition:
              switch.is_on: timer_ringing
            then:
              # Play the alarm sound as an announcement
              - media_player.speaker.play_on_device_media_file:
                  media_file: co_alarm_sound
                  announcement: true
              # Wait until the alarm sound starts playing
              - wait_until:
                  media_player.is_announcing:
              # Wait until the alarm sound stops playing
              - wait_until:
                  not:
                    media_player.is_announcing:
