# CHANGEME: Set these variable to your liking
title: ESPHome Indoor Multi-Sensor
description: Powered by ESPHome and ESP Web Tools
# theme: jekyll-theme-cayman
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme
