name: Release

on:
  pull_request:
    branches:
      - main
    types:
      - closed
  workflow_dispatch:

permissions:
  contents: write

jobs:
  release:
    name: Release
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          fetch-tags: true

      - name: Set Calver Version
        uses: Nelyx/action-calver@v1.1.0
        id: setcalver
        with:
          default_branch: 'refs/heads/main'
          format: 'YYYY.M'
          version_prefix: ''
          
      # - name: CalVer
      #   id: calver
      #   uses: energostack/calver-action@v1.0.4
      #   with:
      #     date_format: "%Y.%-m"
      #     prerelease: ${{ github.event_name == 'workflow_dispatch' }}

      - name: Push Tag
        uses: thejeff77/action-push-tag@v1.0.0
        with:
          tag: ${{ steps.setcalver.outputs.package_version }}
          message: '"${{ steps.setcalver.outputs.package_version }}: PR #${{ github.event.pull_request.number }} - ${{ github.event.pull_request.title }}"'

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.setcalver.outputs.package_version }}
          generate_release_notes: true
          prerelease: ${{ github.event_name == 'workflow_dispatch' }}
