name: Publish Firmware

on:
  release:
    types: [published]
  # push:

permissions:
  contents: write

jobs:
  build-devices:
    name: Build Devices
    uses: esphome/workflows/.github/workflows/build.yml@main
    with:
      files: |
        config/indoor-multi-sensor-pkg-a-radar-c4001.yaml
        config/indoor-multi-sensor-pkg-a-radar-ld2410.yaml
        config/indoor-multi-sensor-pkg-a-radar-ld2450-mtmz.yaml
        config/indoor-multi-sensor-pkg-b-radar-ld2450-stsz.yaml
      esphome-version: latest
      release-summary: ${{ github.event.release.body }}
      release-url: ${{ github.event.release.html_url }}
      release-version: ${{ github.event.release.tag_name }}

  # build-pkg-a-radar-ld2410:
  #   name: Build Package A -  Radar LD2410
  #   uses: esphome/workflows/.github/workflows/build.yml@main
  #   with:
  #     files: config/indoor-multi-sensor-pkg-a-radar-ld2410.yaml
  #     esphome-version: latest
  #     combined-name: indoor-multi-sensor-pkg-a-radar-ld2410
  #     release-summary: ${{ github.event.release.body }}
  #     release-url: ${{ github.event.release.html_url }}
  #     release-version: ${{ github.event.release.tag_name }}

  # build-pkg-a-radar-ld2450-mtmz:
  #   name: Build Package A -  Radar LD2450 Multi-Target Multi-Zone
  #   uses: esphome/workflows/.github/workflows/build.yml@main
  #   with:
  #     files: config/indoor-multi-sensor-pkg-a-radar-ld2450-mtmz.yaml
  #     esphome-version: latest
  #     combined-name: indoor-multi-sensor-pkg-a-radar-ld2450-mtmz
  #     release-summary: ${{ github.event.release.body }}
  #     release-url: ${{ github.event.release.html_url }}
  #     release-version: ${{ github.event.release.tag_name }}

  # build-pkg-a-radar-ld2450-stsz:
  #   name: Build Package A -  Radar LD2450 Single-Target Single-Zone
  #   uses: esphome/workflows/.github/workflows/build.yml@main
  #   with:
  #     files: config/indoor-multi-sensor-pkg-a-radar-ld2450-stsz.yaml
  #     esphome-version: latest
  #     combined-name: indoor-multi-sensor-pkg-a-radar-ld2450-stsz
  #     release-summary: ${{ github.event.release.body }}
  #     release-url: ${{ github.event.release.html_url }}
  #     release-version: ${{ github.event.release.tag_name }}

  # build-pkg-b-radar-c4001:
  #   name: Build Package B -  Radar C4001
  #   uses: esphome/workflows/.github/workflows/build.yml@main
  #   with:
  #     files: config/indoor-multi-sensor-pkg-b-radar-c4001.yaml
  #     esphome-version: latest
  #     combined-name: indoor-multi-sensor-pkg-b-radar-c4001
  #     release-summary: ${{ github.event.release.body }}
  #     release-url: ${{ github.event.release.html_url }}
  #     release-version: ${{ github.event.release.tag_name }}

  # build-pkg-b-radar-ld2410:
  #   name: Build Package B -  Radar LD2410
  #   uses: esphome/workflows/.github/workflows/build.yml@main
  #   with:
  #     files: config/indoor-multi-sensor-pkg-b-radar-ld2410.yaml
  #     esphome-version: latest
  #     combined-name: indoor-multi-sensor-pkg-b-radar-ld2410
  #     release-summary: ${{ github.event.release.body }}
  #     release-url: ${{ github.event.release.html_url }}
  #     release-version: ${{ github.event.release.tag_name }}

  # build-pkg-b-radar-ld2450-mtmz:
  #   name: Build Package B -  Radar LD2450 Multi-Target Multi-Zone
  #   uses: esphome/workflows/.github/workflows/build.yml@main
  #   with:
  #     files: config/indoor-multi-sensor-pkg-b-radar-ld2450-mtmz.yaml
  #     esphome-version: latest
  #     combined-name: indoor-multi-sensor-pkg-b-radar-ld2450-mtmz
  #     release-summary: ${{ github.event.release.body }}
  #     release-url: ${{ github.event.release.html_url }}
  #     release-version: ${{ github.event.release.tag_name }}

  # build-pkg-b-radar-ld2450-stsz:
  #   name: Build Package B -  Radar LD2450 Single-Target Single-Zone
  #   uses: esphome/workflows/.github/workflows/build.yml@main
  #   with:
  #     files: config/indoor-multi-sensor-pkg-b-radar-ld2450-stsz.yaml
  #     esphome-version: latest
  #     combined-name: indoor-multi-sensor-pkg-b-radar-ld2450-stsz
  #     release-summary: ${{ github.event.release.body }}
  #     release-url: ${{ github.event.release.html_url }}
  #     release-version: ${{ github.event.release.tag_name }}

  upload-to-r2:
    name: Upload to R2
    if: github.event_name == 'release' || (github.event_name == 'workflow_dispatch' && github.ref == 'refs/heads/main')
    needs:
      - build-devices
    uses: esphome/workflows/.github/workflows/upload-to-r2.yml@2025.4.0
    with:
      directory: bluetooth-proxy
    secrets: inherit

  upload-to-release:
    name: Upload to Release
    if: github.event_name == 'release'
    uses: esphome/workflows/.github/workflows/upload-to-gh-release.yml@2025.4.0
    needs:
      - build-devices
    with:
      version: ${{ github.event.release.tag_name }}

