name: Publish Firmware

on:
  release:
    types: [published]
  # push:

permissions:
  contents: write

jobs:
  build-pkg-a-radar-c4001:
    name: Build Package A -  Radar C4001
    uses: esphome/workflows/.github/workflows/build.yml@main
    with:
      files: config/indoor-multi-sensor-pkg-a-radar-c4001.yaml
      esphome-version: latest
      combined-name: indoor-multi-sensor-pkg-a-radar-c4001
      release-summary: ${{ github.event.release.body }}
      release-url: ${{ github.event.release.html_url }}
      release-version: ${{ github.event.release.tag_name }}

  build-pkg-a-radar-ld2410:
    name: Build Package A -  Radar LD2410
    uses: esphome/workflows/.github/workflows/build.yml@main
    with:
      files: config/indoor-multi-sensor-pkg-a-radar-ld2410.yaml
      esphome-version: latest
      combined-name: indoor-multi-sensor-pkg-a-radar-ld2410
      release-summary: ${{ github.event.release.body }}
      release-url: ${{ github.event.release.html_url }}
      release-version: ${{ github.event.release.tag_name }}

  # build-pkg-a-radar-ld2450-mtmz:
  #   name: Build Package A -  Radar LD2450 Multi-Target Multi-Zone
  #   uses: esphome/workflows/.github/workflows/build.yml@main
  #   with:
  #     files: config/indoor-multi-sensor-pkg-a-radar-ld2450-mtmz.yaml
  #     esphome-version: latest
  #     combined-name: indoor-multi-sensor-pkg-a-radar-ld2450-mtmz
  #     release-summary: ${{ github.event.release.body }}
  #     release-url: ${{ github.event.release.html_url }}
  #     release-version: ${{ github.event.release.tag_name }}

  # build-pkg-a-radar-ld2450-stsz:
  #   name: Build Package A -  Radar LD2450 Single-Target Single-Zone
  #   uses: esphome/workflows/.github/workflows/build.yml@main
  #   with:
  #     files: config/indoor-multi-sensor-pkg-a-radar-ld2450-stsz.yaml
  #     esphome-version: latest
  #     combined-name: indoor-multi-sensor-pkg-a-radar-ld2450-stsz
  #     release-summary: ${{ github.event.release.body }}
  #     release-url: ${{ github.event.release.html_url }}
  #     release-version: ${{ github.event.release.tag_name }}

  # build-pkg-b-radar-c4001:
  #   name: Build Package B -  Radar C4001
  #   uses: esphome/workflows/.github/workflows/build.yml@main
  #   with:
  #     files: config/indoor-multi-sensor-pkg-b-radar-c4001.yaml
  #     esphome-version: latest
  #     combined-name: indoor-multi-sensor-pkg-b-radar-c4001
  #     release-summary: ${{ github.event.release.body }}
  #     release-url: ${{ github.event.release.html_url }}
  #     release-version: ${{ github.event.release.tag_name }}

  # build-pkg-b-radar-ld2410:
  #   name: Build Package B -  Radar LD2410
  #   uses: esphome/workflows/.github/workflows/build.yml@main
  #   with:
  #     files: config/indoor-multi-sensor-pkg-b-radar-ld2410.yaml
  #     esphome-version: latest
  #     combined-name: indoor-multi-sensor-pkg-b-radar-ld2410
  #     release-summary: ${{ github.event.release.body }}
  #     release-url: ${{ github.event.release.html_url }}
  #     release-version: ${{ github.event.release.tag_name }}

  # build-pkg-b-radar-ld2450-mtmz:
  #   name: Build Package B -  Radar LD2450 Multi-Target Multi-Zone
  #   uses: esphome/workflows/.github/workflows/build.yml@main
  #   with:
  #     files: config/indoor-multi-sensor-pkg-b-radar-ld2450-mtmz.yaml
  #     esphome-version: latest
  #     combined-name: indoor-multi-sensor-pkg-b-radar-ld2450-mtmz
  #     release-summary: ${{ github.event.release.body }}
  #     release-url: ${{ github.event.release.html_url }}
  #     release-version: ${{ github.event.release.tag_name }}

  # build-pkg-b-radar-ld2450-stsz:
  #   name: Build Package B -  Radar LD2450 Single-Target Single-Zone
  #   uses: esphome/workflows/.github/workflows/build.yml@main
  #   with:
  #     files: config/indoor-multi-sensor-pkg-b-radar-ld2450-stsz.yaml
  #     esphome-version: latest
  #     combined-name: indoor-multi-sensor-pkg-b-radar-ld2450-stsz
  #     release-summary: ${{ github.event.release.body }}
  #     release-url: ${{ github.event.release.html_url }}
  #     release-version: ${{ github.event.release.tag_name }}

  upload-to-release:
    name: Upload to Release
    uses: esphome/workflows/.github/workflows/upload-to-gh-release.yml@main
    needs:
      - build-pkg-a-radar-c4001
      # - build-pkg-a-radar-ld2410
      # - build-pkg-a-radar-ld2450-mtmz
      # - build-pkg-a-radar-ld2450-stsz
      # - build-pkg-b-radar-c4001
      # - build-pkg-b-radar-ld2410
      # - build-pkg-b-radar-ld2450-mtmz
      # - build-pkg-b-radar-ld2450-stsz
    with:
      version: ${{ github.event.release.tag_name }}
