name: Release on Merge Pull Request

on:
  pull_request:
    branches:
      - main
    types:
      - closed
  workflow_dispatch:

permissions:
  contents: write

jobs:
  release:
    name: Release
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source  code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
          fetch-tags: true

      - name: Calendar Version
        id: calendar-version
        uses: harm-matthias-harms/calendar-version@v2.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Tag
        uses: thejeff77/action-push-tag@v1.0.0
        with:
          tag: ${{ steps.calendar-version.outputs.new-version }}
          message: '"${{ steps.calendar-version.outputs.new-version }}: PR #${{ github.event.pull_request.number }} - ${{ github.event.pull_request.title }}"'

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.calendar-version.outputs.new-version }}
          generate_release_notes: true
          prerelease: ${{ github.event_name == 'workflow_dispatch' }}
