name: Publish Firmware

on:
  # release:
  #   types: [published]
  workflow_run:
    workflows:
      - Release
    types: [completed]
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  get_release_info:
    name: Get Release Info
    if: ${{ github.event_name == 'workflow_dispatch' || (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success') }}
    runs-on: ubuntu-latest
    steps:
      - name: Get Latest Release
        id: latest_release
        uses: cardinalby/git-get-release-action@1.2.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          latest: true
    outputs:
      summary: ${{ steps.latest_release.outputs.body }}
      url: ${{ steps.latest_release.outputs.html_url }}
      version: ${{ steps.latest_release.outputs.tag_name }}

  build_firmware:
    name: Build Firmware
    uses: esphome/workflows/.github/workflows/build.yml@2025.4.0
    needs:
      - get_release_info
    with:
      files: |
        config/sensor-pkg-a-c4001-esp32-s3.factory.yaml
        config/sensor-pkg-a-ld2410-esp32-s3.factory.yaml
        config/sensor-pkg-a-ld2450-mtmz-esp32-s3.factory.yaml
        config/sensor-pkg-a-ld2450-stsz-esp32-s3.factory.yaml
        config/sensor-pkg-b-c4001-esp32-s3.factory.yaml
        config/sensor-pkg-b-ld2410-esp32-s3.factory.yaml
        config/sensor-pkg-b-ld2450-mtmz-esp32-s3.factory.yaml
        config/sensor-pkg-b-ld2450-stsz-esp32-s3.factory.yaml
      esphome-version: latest
      # combined-name: project-template
      release-summary: ${{ needs.get_release_info.summary }}
      release-url: ${{ needs.get_release_info.url }}
      release-version: ${{ needs.get_release_info.version }}

  upload_firmware_to_release:
    name: Upload Firmware to Release
    uses: esphome/workflows/.github/workflows/upload-to-gh-release.yml@2025.4.0
    needs:
      - get_release_info
      - build_firmware
    with:
      version: ${{ needs.get_release_info.version }}
