name: Testing

on:
  workflow_dispatch:

jobs:
  yamllint:
    name: Test Latest Version
    runs-on: ubuntu-latest
    steps:
      - name: Get latest release
        id: getLatestRelease
        uses: cardinalby/git-get-release-action@1.2.4
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          latest: true
      - name: Example of consumption of the output
        env:
          summary: ${{ steps.getLatestRelease.outputs.body }}
          url: ${{ steps.getLatestRelease.outputs.html_url }}
          version: ${{ steps.getLatestRelease.outputs.tag_name }}
        run: |
          echo "URL=$url\nVersion=$version\nsummary=$summary"
