name: Testing

on:
  workflow_dispatch:

jobs:
  getReleaseInfo:
    name: Get Release Info
    if: ${{ github.event_name == 'workflow_dispatch' || (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success') }}
    runs-on: ubuntu-latest
    steps:
      - name: Get Latest Release
        id: getLatestRelease
        uses: cardinalby/git-get-release-action@1.2.4
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          latest: true
      - name: Example of consumption of the output
        env:
          summary: ${{ steps.getLatestRelease.outputs.body }}
          url: ${{ steps.getLatestRelease.outputs.html_url }}
          version: ${{ steps.getLatestRelease.outputs.tag_name }}
        run: |
          echo "Version${{ steps.getLatestRelease.outputs.tag_name }}|||||||||URL=${{ steps.getLatestRelease.outputs.html_url }}"
    outputs:
      summary: "jsjsjsjsj"
      url: ${{ steps.getLatestRelease.outputs.html_url }}
      version: ${{ steps.getLatestRelease.outputs.tag_name }}
  
  parseReleaseInfo:
    name: Parse Release Info
    runs-on: ubuntu-latest
    needs: getReleaseInfo
    steps:
      - name: Parse Latest Release
        run: echo "version=${{needs.getReleaseInfo.outputs.version}}           summary=${{needs.getReleaseInfo.outputs.summary}}                                   Needs=${{ toJSON(needs) }}"
