name: Testing

on:
  workflow_dispatch:

jobs:
  testLatestVersion:
    name: Test Latest Version
    runs-on: ubuntu-latest
    steps:
      - name: Get Latest Release
        id: getLatestRelease
        uses: cardinalby/git-get-release-action@1.2.4
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          latest: true
      # - name: Build Firmware
      #   id: buildFirmware
      #   uses: esphome/workflows/.github/workflows/build.yml@2025.4.0
      #   with:
      #     files: |
      #       config/sensor-pkg-a-c4001-esp32-s3.factory.yaml
      #       config/sensor-pkg-a-ld2410-esp32-s3.factory.yaml
      #       config/sensor-pkg-a-ld2450-mtmz-esp32-s3.factory.yaml
      #       config/sensor-pkg-a-ld2450-stsz-esp32-s3.factory.yaml
      #       config/sensor-pkg-b-c4001-esp32-s3.factory.yaml
      #       config/sensor-pkg-b-ld2410-esp32-s3.factory.yaml
      #       config/sensor-pkg-b-ld2450-mtmz-esp32-s3.factory.yaml
      #       config/sensor-pkg-b-ld2450-stsz-esp32-s3.factory.yaml
      #     esphome-version: latest
      #     # combined-name: project-template
      #     release-summary: ${{ steps.getLatestRelease.outputs.body }}
      #     release-url: ${{ steps.getLatestRelease.outputs.html_url }}
      #     release-version: ${{ steps.getLatestRelease.outputs.tag_name }}
      - name: Upload Firmware to Release
        id: uploadFirmwareToRelease
        uses: esphome/workflows/.github/workflows/upload-to-gh-release.yml@2025.4.0
        with:
          version: ${{ steps.getLatestRelease.outputs.tag_name }}
